spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: "jdbc:postgresql://localhost:5435/ggu_bot_db"
    username: "postgres"
    password: "1111"
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
server:
  port: 8084

schedule:
  delivery-time: 0 35 18 * * *